FROM node:22

WORKDIR /usr/src/app

RUN npm install -g pnpm
RUN npm install -g ts-node

COPY package*.json ./

RUN pnpm install
RUN pnpm rebuild bcrypt

COPY . .

RUN pnpm build

EXPOSE 3000

CMD ["node", "dist/main"]