version: '3.8'
services:
  cp-hub-postgres:
    image: postgres:17
    container_name: cp-hub-postgres
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cp-hub-nest:
    env_file: ../.env
    build:
      context: ../
      dockerfile: ops/Dockerfile
    container_name: cp-hub-nest
    depends_on:
      - cp-hub-postgres

  cp-hub-nginx:
    image: nginx:latest
    container_name: cp-hub-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro   # location of SSL certificates
    depends_on:
      - cp-hub-nest

volumes:
  pgdata:
